### PR TITLE
Add processing data in models

### PR DESCRIPTION
**Pull request by alanluqman**
## Description
In this PR, I created the data processing in models

### CODE REVIEW

**Review by Danieldotcomcoder — COMMENTED** [review]
Hi @alanluqman , 


While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't include a professional Readme File , Kindly refer to this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) 👍 👍  to add a good Readme File 😄 😄 then submit again, Thank you 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by alanluqman** [comment]
Dear @Danieldotcomcoder, Thanks for your review

**Review by MahmoudBakr23 — APPROVED** [review]
Hi @alanluqman 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done creating your models' associations correctly
- Great job using rails helper methods `after_save`
- Nice work managing the counter methods
- Correct Linters
- Descriptive PR

**Optional**
- Please add a valid MIT link in the README file

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alanluqman** [comment]
Thanks for your review

**Pull request merged**
